# https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml

# Theme settings
remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: # air, aqua, contrast, dark, dirt, neon, mint, plum, sunrise

# Site settings
title: A Blog by Petr Řehoř # A Blog by Petr Řehoř
title_separator: "|"
subtitle: # site tagline that appears below site title in masthead
name: Petr Řehoř
# description: >- # this means to ignore newlines
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
teaser: # path of fallback teaser image
logo: # /assets/images/prehor-avatar.png # path of logo image to display in the masthead
breadcrumbs: false
search: true
search_full_content: true
# google_site_verification: # SEO Related

# Social sharing

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-316217-4"
    anonymize_ip: true
head_scripts:
  - https://cmp.osano.com/AzZcj2RuRfyUG1SCq/3dc429a1-adaa-409f-990c-2ff5842cc5dd/osano.js

# Site author
author:
  name: Petr Řehoř
  avatar: /assets/images/prehor-avatar.png
  bio: |
    <p style="margin-bottom:0;padding-bottom:0;">
      Any decent answer to an interesting question begins, "It depends..."
    </p>
    <p style="margin-top:0;padding-top:0;text-align:right;">
      -- <a href="https://twitter.com/kentbeck/status/596007846887628801">Kent Beck</a>
    </p>
  location: Borovany, CZ
  github: prehor
  linkedin: prehor
  # twitter: PetrRehor

# Site footer

# Reading files
include:
  - .htaccess
  - _pages
exclude:
  - .gitignore
  - docker-compose.yml
  - LICENSE
  - Makefile
  - README.md
encoding: utf-8
keep_files:
  - .git

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
# Sass/SCSS

# Outputting
paginate_path: /page:num/
paginate: 5 # amount of posts to show
timezone: Europe/Prague

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# Archives
# category_archive:
#   type: liquid
#   path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: _pages
      type: pages
    values:
      layout: single
      author_profile: true
